name : Build docker Image
on: 
  push:
    branches: [ main ]

jobs: 
  build-and-push: 
    runs-on: ubuntu-latest 

    steps: 
      #Setup 1 : download your code 
      - name : Checkout code 
        uses: actions/checkout@v2

      #Setup 2 : Login to docker hub
      - name : Login to Docker hub 
        uses: docker/login-action@v2 
        with: 
        username : ${{ secrets.DOCKER_USERNAME}}
        password : ${{ secrets.DOCKER_PASSWORD}}

      #Setup 3 : build and push docker image 
      - name : Build and Push Docker image
        run : |
          docker build -t my-docker-image:latest .
          docker tag my-docker-image:latest ${{ secrets.DOCKER_USERNAME}}/my-docker-image:latest
          docker push ${{ secrets.DOCKER_USERNAME}}/my-docker-image:latest